//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oleit.AS.Service.LogicService.EndPeriodAccessReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EndPeriodAccessReference.IEndPeriodAccess")]
    public interface IEndPeriodAccess {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEndPeriodAccess/Query", ReplyAction="http://tempuri.org/IEndPeriodAccess/QueryResponse")]
        Oleit.AS.Service.DataObject.EndPeriod[] Query(Oleit.AS.Service.DataObject.EndPeriod endPeriod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEndPeriodAccess/Insert", ReplyAction="http://tempuri.org/IEndPeriodAccess/InsertResponse")]
        void Insert(Oleit.AS.Service.DataObject.EndPeriod endPeriod);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEndPeriodAccessChannel : Oleit.AS.Service.LogicService.EndPeriodAccessReference.IEndPeriodAccess, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EndPeriodAccessClient : System.ServiceModel.ClientBase<Oleit.AS.Service.LogicService.EndPeriodAccessReference.IEndPeriodAccess>, Oleit.AS.Service.LogicService.EndPeriodAccessReference.IEndPeriodAccess {
        
        public EndPeriodAccessClient() {
        }
        
        public EndPeriodAccessClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EndPeriodAccessClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EndPeriodAccessClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EndPeriodAccessClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Oleit.AS.Service.DataObject.EndPeriod[] Query(Oleit.AS.Service.DataObject.EndPeriod endPeriod) {
            return base.Channel.Query(endPeriod);
        }
        
        public void Insert(Oleit.AS.Service.DataObject.EndPeriod endPeriod) {
            base.Channel.Insert(endPeriod);
        }
    }
}
