//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting_System.EndPeriodServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EndPeriodServiceReference.IEndPeriodService")]
    public interface IEndPeriodService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEndPeriodService/GetEndPeriodRate", ReplyAction="http://tempuri.org/IEndPeriodService/GetEndPeriodRateResponse")]
        Oleit.AS.Service.DataObject.EndPeriod[] GetEndPeriodRate(Oleit.AS.Service.DataObject.Currency Currency);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEndPeriodService/InsertEndPeriod", ReplyAction="http://tempuri.org/IEndPeriodService/InsertEndPeriodResponse")]
        bool InsertEndPeriod(Oleit.AS.Service.DataObject.EndPeriod endPeriod);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEndPeriodServiceChannel : Accounting_System.EndPeriodServiceReference.IEndPeriodService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EndPeriodServiceClient : System.ServiceModel.ClientBase<Accounting_System.EndPeriodServiceReference.IEndPeriodService>, Accounting_System.EndPeriodServiceReference.IEndPeriodService {
        
        public EndPeriodServiceClient() {
        }
        
        public EndPeriodServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EndPeriodServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EndPeriodServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EndPeriodServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Oleit.AS.Service.DataObject.EndPeriod[] GetEndPeriodRate(Oleit.AS.Service.DataObject.Currency Currency) {
            return base.Channel.GetEndPeriodRate(Currency);
        }
        
        public bool InsertEndPeriod(Oleit.AS.Service.DataObject.EndPeriod endPeriod) {
            return base.Channel.InsertEndPeriod(endPeriod);
        }
    }
}
