//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oleit.AS.Service.LogicService.WeeklySummaryReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WeeklySummaryReference.IWeeklySummaryAccess")]
    public interface IWeeklySummaryAccess {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeeklySummaryAccess/Insert1", ReplyAction="http://tempuri.org/IWeeklySummaryAccess/Insert1Response")]
        void Insert1(Oleit.AS.Service.DataObject.WeeklySummary weeklySummary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeeklySummaryAccess/Insert2", ReplyAction="http://tempuri.org/IWeeklySummaryAccess/Insert2Response")]
        void Insert2(Oleit.AS.Service.DataObject.WeeklySummary[] weeklySummaryCollection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeeklySummaryAccess/Query1", ReplyAction="http://tempuri.org/IWeeklySummaryAccess/Query1Response")]
        Oleit.AS.Service.DataObject.WeeklySummary[] Query1(int entityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeeklySummaryAccess/Query", ReplyAction="http://tempuri.org/IWeeklySummaryAccess/QueryResponse")]
        Oleit.AS.Service.DataObject.WeeklySummary[] Query(int periodID, int entityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeeklySummaryAccess/QuerybyPeriod", ReplyAction="http://tempuri.org/IWeeklySummaryAccess/QuerybyPeriodResponse")]
        Oleit.AS.Service.DataObject.WeeklySummary[] QuerybyPeriod(int periodID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeeklySummaryAccess/QueryAll", ReplyAction="http://tempuri.org/IWeeklySummaryAccess/QueryAllResponse")]
        Oleit.AS.Service.DataObject.WeeklySummary[] QueryAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeeklySummaryAccess/Query2", ReplyAction="http://tempuri.org/IWeeklySummaryAccess/Query2Response")]
        Oleit.AS.Service.DataObject.WeeklySummary[] Query2(int periodID, int[] entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeeklySummaryAccess/Update1", ReplyAction="http://tempuri.org/IWeeklySummaryAccess/Update1Response")]
        void Update1(Oleit.AS.Service.DataObject.WeeklySummary weeklySummary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeeklySummaryAccess/Update2", ReplyAction="http://tempuri.org/IWeeklySummaryAccess/Update2Response")]
        void Update2(Oleit.AS.Service.DataObject.WeeklySummary[] weeklySummaryCollection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeeklySummaryAccess/SubTotalConfirm", ReplyAction="http://tempuri.org/IWeeklySummaryAccess/SubTotalConfirmResponse")]
        void SubTotalConfirm(Oleit.AS.Service.DataObject.WeeklySummary[] weeklySummaryCollection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeeklySummaryAccess/WinLossConfirm", ReplyAction="http://tempuri.org/IWeeklySummaryAccess/WinLossConfirmResponse")]
        void WinLossConfirm(Oleit.AS.Service.DataObject.WeeklySummary[] weeklySummaryCollection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeeklySummaryAccess/IsWeeklyConfirm", ReplyAction="http://tempuri.org/IWeeklySummaryAccess/IsWeeklyConfirmResponse")]
        bool IsWeeklyConfirm(int periodID, int entityID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWeeklySummaryAccessChannel : Oleit.AS.Service.LogicService.WeeklySummaryReference.IWeeklySummaryAccess, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WeeklySummaryAccessClient : System.ServiceModel.ClientBase<Oleit.AS.Service.LogicService.WeeklySummaryReference.IWeeklySummaryAccess>, Oleit.AS.Service.LogicService.WeeklySummaryReference.IWeeklySummaryAccess {
        
        public WeeklySummaryAccessClient() {
        }
        
        public WeeklySummaryAccessClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WeeklySummaryAccessClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeeklySummaryAccessClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeeklySummaryAccessClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Insert1(Oleit.AS.Service.DataObject.WeeklySummary weeklySummary) {
            base.Channel.Insert1(weeklySummary);
        }
        
        public void Insert2(Oleit.AS.Service.DataObject.WeeklySummary[] weeklySummaryCollection) {
            base.Channel.Insert2(weeklySummaryCollection);
        }
        
        public Oleit.AS.Service.DataObject.WeeklySummary[] Query1(int entityID) {
            return base.Channel.Query1(entityID);
        }
        
        public Oleit.AS.Service.DataObject.WeeklySummary[] Query(int periodID, int entityID) {
            return base.Channel.Query(periodID, entityID);
        }
        
        public Oleit.AS.Service.DataObject.WeeklySummary[] QuerybyPeriod(int periodID) {
            return base.Channel.QuerybyPeriod(periodID);
        }
        
        public Oleit.AS.Service.DataObject.WeeklySummary[] QueryAll() {
            return base.Channel.QueryAll();
        }
        
        public Oleit.AS.Service.DataObject.WeeklySummary[] Query2(int periodID, int[] entity) {
            return base.Channel.Query2(periodID, entity);
        }
        
        public void Update1(Oleit.AS.Service.DataObject.WeeklySummary weeklySummary) {
            base.Channel.Update1(weeklySummary);
        }
        
        public void Update2(Oleit.AS.Service.DataObject.WeeklySummary[] weeklySummaryCollection) {
            base.Channel.Update2(weeklySummaryCollection);
        }
        
        public void SubTotalConfirm(Oleit.AS.Service.DataObject.WeeklySummary[] weeklySummaryCollection) {
            base.Channel.SubTotalConfirm(weeklySummaryCollection);
        }
        
        public void WinLossConfirm(Oleit.AS.Service.DataObject.WeeklySummary[] weeklySummaryCollection) {
            base.Channel.WinLossConfirm(weeklySummaryCollection);
        }
        
        public bool IsWeeklyConfirm(int periodID, int entityID) {
            return base.Channel.IsWeeklyConfirm(periodID, entityID);
        }
    }
}
