//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting_System.CurrencyServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CurrencyServiceReference.ICurrencyService")]
    public interface ICurrencyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/NewCurrency", ReplyAction="http://tempuri.org/ICurrencyService/NewCurrencyResponse")]
        void NewCurrency(Oleit.AS.Service.DataObject.Currency currency);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/DelCurrency", ReplyAction="http://tempuri.org/ICurrencyService/DelCurrencyResponse")]
        void DelCurrency(Oleit.AS.Service.DataObject.Currency currency);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/AllCurrency", ReplyAction="http://tempuri.org/ICurrencyService/AllCurrencyResponse")]
        Oleit.AS.Service.DataObject.Currency[] AllCurrency();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICurrencyServiceChannel : Accounting_System.CurrencyServiceReference.ICurrencyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CurrencyServiceClient : System.ServiceModel.ClientBase<Accounting_System.CurrencyServiceReference.ICurrencyService>, Accounting_System.CurrencyServiceReference.ICurrencyService {
        
        public CurrencyServiceClient() {
        }
        
        public CurrencyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CurrencyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CurrencyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CurrencyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void NewCurrency(Oleit.AS.Service.DataObject.Currency currency) {
            base.Channel.NewCurrency(currency);
        }
        
        public void DelCurrency(Oleit.AS.Service.DataObject.Currency currency) {
            base.Channel.DelCurrency(currency);
        }
        
        public Oleit.AS.Service.DataObject.Currency[] AllCurrency() {
            return base.Channel.AllCurrency();
        }
    }
}
