//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting_System.SystemDataServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SystemDataServiceReference.ISystemDataService")]
    public interface ISystemDataService {
        
        // CODEGEN: Parameter 'GetUserMLJEntityResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystemDataService/GetUserMLJEntity", ReplyAction="http://tempuri.org/ISystemDataService/GetUserMLJEntityResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Accounting_System.SystemDataServiceReference.GetUserMLJEntityResponse GetUserMLJEntity(Accounting_System.SystemDataServiceReference.GetUserMLJEntityRequest request);
        
        // CODEGEN: Parameter 'LoadWinAndLossLogResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystemDataService/LoadWinAndLossLog", ReplyAction="http://tempuri.org/ISystemDataService/LoadWinAndLossLogResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Accounting_System.SystemDataServiceReference.LoadWinAndLossLogResponse LoadWinAndLossLog(Accounting_System.SystemDataServiceReference.LoadWinAndLossLogRequest request);
        
        // CODEGEN: Parameter 'QueryRoleMenuRelationResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystemDataService/QueryRoleMenuRelation", ReplyAction="http://tempuri.org/ISystemDataService/QueryRoleMenuRelationResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Accounting_System.SystemDataServiceReference.QueryRoleMenuRelationResponse QueryRoleMenuRelation(Accounting_System.SystemDataServiceReference.QueryRoleMenuRelationRequest request);
        
        // CODEGEN: Parameter 'QueryRoleUserRelationResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystemDataService/QueryRoleUserRelation", ReplyAction="http://tempuri.org/ISystemDataService/QueryRoleUserRelationResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Accounting_System.SystemDataServiceReference.QueryRoleUserRelationResponse QueryRoleUserRelation(Accounting_System.SystemDataServiceReference.QueryRoleUserRelationRequest request);
        
        // CODEGEN: Parameter 'GetAccountStatusLogResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystemDataService/GetAccountStatusLog", ReplyAction="http://tempuri.org/ISystemDataService/GetAccountStatusLogResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Accounting_System.SystemDataServiceReference.GetAccountStatusLogResponse GetAccountStatusLog(Accounting_System.SystemDataServiceReference.GetAccountStatusLogRequest request);
        
        // CODEGEN: Parameter 'GetMLJLogResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystemDataService/GetMLJLog", ReplyAction="http://tempuri.org/ISystemDataService/GetMLJLogResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Accounting_System.SystemDataServiceReference.GetMLJLogResponse GetMLJLog(Accounting_System.SystemDataServiceReference.GetMLJLogRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserMLJEntity", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUserMLJEntityRequest {
        
        public GetUserMLJEntityRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserMLJEntityResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUserMLJEntityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet GetUserMLJEntityResult;
        
        public GetUserMLJEntityResponse() {
        }
        
        public GetUserMLJEntityResponse(System.Data.DataSet GetUserMLJEntityResult) {
            this.GetUserMLJEntityResult = GetUserMLJEntityResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadWinAndLossLog", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoadWinAndLossLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int entityID;
        
        public LoadWinAndLossLogRequest() {
        }
        
        public LoadWinAndLossLogRequest(int entityID) {
            this.entityID = entityID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadWinAndLossLogResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoadWinAndLossLogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet LoadWinAndLossLogResult;
        
        public LoadWinAndLossLogResponse() {
        }
        
        public LoadWinAndLossLogResponse(System.Data.DataSet LoadWinAndLossLogResult) {
            this.LoadWinAndLossLogResult = LoadWinAndLossLogResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryRoleMenuRelation", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QueryRoleMenuRelationRequest {
        
        public QueryRoleMenuRelationRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryRoleMenuRelationResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QueryRoleMenuRelationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet QueryRoleMenuRelationResult;
        
        public QueryRoleMenuRelationResponse() {
        }
        
        public QueryRoleMenuRelationResponse(System.Data.DataSet QueryRoleMenuRelationResult) {
            this.QueryRoleMenuRelationResult = QueryRoleMenuRelationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryRoleUserRelation", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QueryRoleUserRelationRequest {
        
        public QueryRoleUserRelationRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryRoleUserRelationResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QueryRoleUserRelationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet QueryRoleUserRelationResult;
        
        public QueryRoleUserRelationResponse() {
        }
        
        public QueryRoleUserRelationResponse(System.Data.DataSet QueryRoleUserRelationResult) {
            this.QueryRoleUserRelationResult = QueryRoleUserRelationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAccountStatusLog", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAccountStatusLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int entityid;
        
        public GetAccountStatusLogRequest() {
        }
        
        public GetAccountStatusLogRequest(int entityid) {
            this.entityid = entityid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAccountStatusLogResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAccountStatusLogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet GetAccountStatusLogResult;
        
        public GetAccountStatusLogResponse() {
        }
        
        public GetAccountStatusLogResponse(System.Data.DataSet GetAccountStatusLogResult) {
            this.GetAccountStatusLogResult = GetAccountStatusLogResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMLJLog", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMLJLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int periodId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string entityName;
        
        public GetMLJLogRequest() {
        }
        
        public GetMLJLogRequest(int periodId, string entityName) {
            this.periodId = periodId;
            this.entityName = entityName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMLJLogResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetMLJLogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet GetMLJLogResult;
        
        public GetMLJLogResponse() {
        }
        
        public GetMLJLogResponse(System.Data.DataSet GetMLJLogResult) {
            this.GetMLJLogResult = GetMLJLogResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISystemDataServiceChannel : Accounting_System.SystemDataServiceReference.ISystemDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SystemDataServiceClient : System.ServiceModel.ClientBase<Accounting_System.SystemDataServiceReference.ISystemDataService>, Accounting_System.SystemDataServiceReference.ISystemDataService {
        
        public SystemDataServiceClient() {
        }
        
        public SystemDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SystemDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SystemDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SystemDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Accounting_System.SystemDataServiceReference.GetUserMLJEntityResponse Accounting_System.SystemDataServiceReference.ISystemDataService.GetUserMLJEntity(Accounting_System.SystemDataServiceReference.GetUserMLJEntityRequest request) {
            return base.Channel.GetUserMLJEntity(request);
        }
        
        public System.Data.DataSet GetUserMLJEntity() {
            Accounting_System.SystemDataServiceReference.GetUserMLJEntityRequest inValue = new Accounting_System.SystemDataServiceReference.GetUserMLJEntityRequest();
            Accounting_System.SystemDataServiceReference.GetUserMLJEntityResponse retVal = ((Accounting_System.SystemDataServiceReference.ISystemDataService)(this)).GetUserMLJEntity(inValue);
            return retVal.GetUserMLJEntityResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Accounting_System.SystemDataServiceReference.LoadWinAndLossLogResponse Accounting_System.SystemDataServiceReference.ISystemDataService.LoadWinAndLossLog(Accounting_System.SystemDataServiceReference.LoadWinAndLossLogRequest request) {
            return base.Channel.LoadWinAndLossLog(request);
        }
        
        public System.Data.DataSet LoadWinAndLossLog(int entityID) {
            Accounting_System.SystemDataServiceReference.LoadWinAndLossLogRequest inValue = new Accounting_System.SystemDataServiceReference.LoadWinAndLossLogRequest();
            inValue.entityID = entityID;
            Accounting_System.SystemDataServiceReference.LoadWinAndLossLogResponse retVal = ((Accounting_System.SystemDataServiceReference.ISystemDataService)(this)).LoadWinAndLossLog(inValue);
            return retVal.LoadWinAndLossLogResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Accounting_System.SystemDataServiceReference.QueryRoleMenuRelationResponse Accounting_System.SystemDataServiceReference.ISystemDataService.QueryRoleMenuRelation(Accounting_System.SystemDataServiceReference.QueryRoleMenuRelationRequest request) {
            return base.Channel.QueryRoleMenuRelation(request);
        }
        
        public System.Data.DataSet QueryRoleMenuRelation() {
            Accounting_System.SystemDataServiceReference.QueryRoleMenuRelationRequest inValue = new Accounting_System.SystemDataServiceReference.QueryRoleMenuRelationRequest();
            Accounting_System.SystemDataServiceReference.QueryRoleMenuRelationResponse retVal = ((Accounting_System.SystemDataServiceReference.ISystemDataService)(this)).QueryRoleMenuRelation(inValue);
            return retVal.QueryRoleMenuRelationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Accounting_System.SystemDataServiceReference.QueryRoleUserRelationResponse Accounting_System.SystemDataServiceReference.ISystemDataService.QueryRoleUserRelation(Accounting_System.SystemDataServiceReference.QueryRoleUserRelationRequest request) {
            return base.Channel.QueryRoleUserRelation(request);
        }
        
        public System.Data.DataSet QueryRoleUserRelation() {
            Accounting_System.SystemDataServiceReference.QueryRoleUserRelationRequest inValue = new Accounting_System.SystemDataServiceReference.QueryRoleUserRelationRequest();
            Accounting_System.SystemDataServiceReference.QueryRoleUserRelationResponse retVal = ((Accounting_System.SystemDataServiceReference.ISystemDataService)(this)).QueryRoleUserRelation(inValue);
            return retVal.QueryRoleUserRelationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Accounting_System.SystemDataServiceReference.GetAccountStatusLogResponse Accounting_System.SystemDataServiceReference.ISystemDataService.GetAccountStatusLog(Accounting_System.SystemDataServiceReference.GetAccountStatusLogRequest request) {
            return base.Channel.GetAccountStatusLog(request);
        }
        
        public System.Data.DataSet GetAccountStatusLog(int entityid) {
            Accounting_System.SystemDataServiceReference.GetAccountStatusLogRequest inValue = new Accounting_System.SystemDataServiceReference.GetAccountStatusLogRequest();
            inValue.entityid = entityid;
            Accounting_System.SystemDataServiceReference.GetAccountStatusLogResponse retVal = ((Accounting_System.SystemDataServiceReference.ISystemDataService)(this)).GetAccountStatusLog(inValue);
            return retVal.GetAccountStatusLogResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Accounting_System.SystemDataServiceReference.GetMLJLogResponse Accounting_System.SystemDataServiceReference.ISystemDataService.GetMLJLog(Accounting_System.SystemDataServiceReference.GetMLJLogRequest request) {
            return base.Channel.GetMLJLog(request);
        }
        
        public System.Data.DataSet GetMLJLog(int periodId, string entityName) {
            Accounting_System.SystemDataServiceReference.GetMLJLogRequest inValue = new Accounting_System.SystemDataServiceReference.GetMLJLogRequest();
            inValue.periodId = periodId;
            inValue.entityName = entityName;
            Accounting_System.SystemDataServiceReference.GetMLJLogResponse retVal = ((Accounting_System.SystemDataServiceReference.ISystemDataService)(this)).GetMLJLog(inValue);
            return retVal.GetMLJLogResult;
        }
    }
}
