//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting_System.SettleServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SettleServiceReference.ISettleService")]
    public interface ISettleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISettleService/WeeklySummarize", ReplyAction="http://tempuri.org/ISettleService/WeeklySummarizeResponse")]
        void WeeklySummarize(Oleit.AS.Service.DataObject.Entity entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISettleService/WinLossConfirm", ReplyAction="http://tempuri.org/ISettleService/WinLossConfirmResponse")]
        void WinLossConfirm(Oleit.AS.Service.DataObject.WeeklySummary[] weeklySummaryCollection, int recordID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISettleService/CloseEntry", ReplyAction="http://tempuri.org/ISettleService/CloseEntryResponse")]
        bool CloseEntry(int userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISettleService/ReverseClosing", ReplyAction="http://tempuri.org/ISettleService/ReverseClosingResponse")]
        void ReverseClosing();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISettleService/TransferPL", ReplyAction="http://tempuri.org/ISettleService/TransferPLResponse")]
        void TransferPL(Oleit.AS.Service.DataObject.Period period);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISettleService/TransferConfirm", ReplyAction="http://tempuri.org/ISettleService/TransferConfirmResponse")]
        void TransferConfirm(Oleit.AS.Service.DataObject.Record roecord, int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISettleService/TransactionConfirm", ReplyAction="http://tempuri.org/ISettleService/TransactionConfirmResponse")]
        void TransactionConfirm(Oleit.AS.Service.DataObject.WeeklySummary[] weeklySummaryCollection);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISettleServiceChannel : Accounting_System.SettleServiceReference.ISettleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SettleServiceClient : System.ServiceModel.ClientBase<Accounting_System.SettleServiceReference.ISettleService>, Accounting_System.SettleServiceReference.ISettleService {
        
        public SettleServiceClient() {
        }
        
        public SettleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SettleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SettleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SettleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void WeeklySummarize(Oleit.AS.Service.DataObject.Entity entity) {
            base.Channel.WeeklySummarize(entity);
        }
        
        public void WinLossConfirm(Oleit.AS.Service.DataObject.WeeklySummary[] weeklySummaryCollection, int recordID) {
            base.Channel.WinLossConfirm(weeklySummaryCollection, recordID);
        }
        
        public bool CloseEntry(int userid) {
            return base.Channel.CloseEntry(userid);
        }
        
        public void ReverseClosing() {
            base.Channel.ReverseClosing();
        }
        
        public void TransferPL(Oleit.AS.Service.DataObject.Period period) {
            base.Channel.TransferPL(period);
        }
        
        public void TransferConfirm(Oleit.AS.Service.DataObject.Record roecord, int userID) {
            base.Channel.TransferConfirm(roecord, userID);
        }
        
        public void TransactionConfirm(Oleit.AS.Service.DataObject.WeeklySummary[] weeklySummaryCollection) {
            base.Channel.TransactionConfirm(weeklySummaryCollection);
        }
    }
}
