//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oleit.AS.Service.LogicService.TransferAccessReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TransferAccessReference.ITransferAccess")]
    public interface ITransferAccess {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransferAccess/Insert", ReplyAction="http://tempuri.org/ITransferAccess/InsertResponse")]
        int Insert(Oleit.AS.Service.DataObject.Record record, Oleit.AS.Service.DataObject.Transfer transfer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransferAccess/InsertDetail", ReplyAction="http://tempuri.org/ITransferAccess/InsertDetailResponse")]
        void InsertDetail(Oleit.AS.Service.DataObject.TransferDetail transferdetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransferAccess/Update", ReplyAction="http://tempuri.org/ITransferAccess/UpdateResponse")]
        void Update(Oleit.AS.Service.DataObject.Transfer transfer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransferAccess/UpdateDetail", ReplyAction="http://tempuri.org/ITransferAccess/UpdateDetailResponse")]
        void UpdateDetail(Oleit.AS.Service.DataObject.TransferDetail transferdetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransferAccess/UpdateDetailCollection", ReplyAction="http://tempuri.org/ITransferAccess/UpdateDetailCollectionResponse")]
        void UpdateDetailCollection(Oleit.AS.Service.DataObject.TransferDetail[] transferdetailcollection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransferAccess/Query", ReplyAction="http://tempuri.org/ITransferAccess/QueryResponse")]
        Oleit.AS.Service.DataObject.Transfer[] Query(int recordID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransferAccess/QueryDetailCollection", ReplyAction="http://tempuri.org/ITransferAccess/QueryDetailCollectionResponse")]
        Oleit.AS.Service.DataObject.TransferDetail[] QueryDetailCollection(int recordID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransferAccess/QueryCollectionByToEntityID", ReplyAction="http://tempuri.org/ITransferAccess/QueryCollectionByToEntityIDResponse")]
        Oleit.AS.Service.DataObject.Transfer[] QueryCollectionByToEntityID(int EntityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransferAccess/QueryDetailCollectionByToEntityID", ReplyAction="http://tempuri.org/ITransferAccess/QueryDetailCollectionByToEntityIDResponse")]
        Oleit.AS.Service.DataObject.TransferDetail[] QueryDetailCollectionByToEntityID(int EntityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransferAccess/QueryByEntityID", ReplyAction="http://tempuri.org/ITransferAccess/QueryByEntityIDResponse")]
        Oleit.AS.Service.DataObject.TransferDetail[] QueryByEntityID(int EntityID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITransferAccessChannel : Oleit.AS.Service.LogicService.TransferAccessReference.ITransferAccess, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TransferAccessClient : System.ServiceModel.ClientBase<Oleit.AS.Service.LogicService.TransferAccessReference.ITransferAccess>, Oleit.AS.Service.LogicService.TransferAccessReference.ITransferAccess {
        
        public TransferAccessClient() {
        }
        
        public TransferAccessClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TransferAccessClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransferAccessClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransferAccessClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Insert(Oleit.AS.Service.DataObject.Record record, Oleit.AS.Service.DataObject.Transfer transfer) {
            return base.Channel.Insert(record, transfer);
        }
        
        public void InsertDetail(Oleit.AS.Service.DataObject.TransferDetail transferdetail) {
            base.Channel.InsertDetail(transferdetail);
        }
        
        public void Update(Oleit.AS.Service.DataObject.Transfer transfer) {
            base.Channel.Update(transfer);
        }
        
        public void UpdateDetail(Oleit.AS.Service.DataObject.TransferDetail transferdetail) {
            base.Channel.UpdateDetail(transferdetail);
        }
        
        public void UpdateDetailCollection(Oleit.AS.Service.DataObject.TransferDetail[] transferdetailcollection) {
            base.Channel.UpdateDetailCollection(transferdetailcollection);
        }
        
        public Oleit.AS.Service.DataObject.Transfer[] Query(int recordID) {
            return base.Channel.Query(recordID);
        }
        
        public Oleit.AS.Service.DataObject.TransferDetail[] QueryDetailCollection(int recordID) {
            return base.Channel.QueryDetailCollection(recordID);
        }
        
        public Oleit.AS.Service.DataObject.Transfer[] QueryCollectionByToEntityID(int EntityID) {
            return base.Channel.QueryCollectionByToEntityID(EntityID);
        }
        
        public Oleit.AS.Service.DataObject.TransferDetail[] QueryDetailCollectionByToEntityID(int EntityID) {
            return base.Channel.QueryDetailCollectionByToEntityID(EntityID);
        }
        
        public Oleit.AS.Service.DataObject.TransferDetail[] QueryByEntityID(int EntityID) {
            return base.Channel.QueryByEntityID(EntityID);
        }
    }
}
