//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oleit.AS.Service.LogicService.UserAccessReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserAccessReference.IUserAccess")]
    public interface IUserAccess {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAccess/Insertuser", ReplyAction="http://tempuri.org/IUserAccess/InsertuserResponse")]
        void Insertuser(Oleit.AS.Service.DataObject.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAccess/InsertuserCollection", ReplyAction="http://tempuri.org/IUserAccess/InsertuserCollectionResponse")]
        void InsertuserCollection(Oleit.AS.Service.DataObject.User[] userCollection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAccess/QueryuserID", ReplyAction="http://tempuri.org/IUserAccess/QueryuserIDResponse")]
        Oleit.AS.Service.DataObject.User[] QueryuserID(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAccess/QueryuserName", ReplyAction="http://tempuri.org/IUserAccess/QueryuserNameResponse")]
        Oleit.AS.Service.DataObject.User[] QueryuserName(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAccess/QueryAll", ReplyAction="http://tempuri.org/IUserAccess/QueryAllResponse")]
        Oleit.AS.Service.DataObject.User[] QueryAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAccess/Updateuser", ReplyAction="http://tempuri.org/IUserAccess/UpdateuserResponse")]
        void Updateuser(Oleit.AS.Service.DataObject.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAccess/UpdateuserCollection", ReplyAction="http://tempuri.org/IUserAccess/UpdateuserCollectionResponse")]
        void UpdateuserCollection(Oleit.AS.Service.DataObject.User[] userCollection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAccess/Disable", ReplyAction="http://tempuri.org/IUserAccess/DisableResponse")]
        void Disable(Oleit.AS.Service.DataObject.User[] userCollection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAccess/DisableUser", ReplyAction="http://tempuri.org/IUserAccess/DisableUserResponse")]
        bool DisableUser(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAccess/ChangePassword", ReplyAction="http://tempuri.org/IUserAccess/ChangePasswordResponse")]
        void ChangePassword(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAccess/UpdateRoles", ReplyAction="http://tempuri.org/IUserAccess/UpdateRolesResponse")]
        void UpdateRoles(string userName, Oleit.AS.Service.DataObject.Role role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAccess/UpdaterolesCollection", ReplyAction="http://tempuri.org/IUserAccess/UpdaterolesCollectionResponse")]
        void UpdaterolesCollection(string userName, Oleit.AS.Service.DataObject.Role[] roleCollection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAccess/QueryRoles", ReplyAction="http://tempuri.org/IUserAccess/QueryRolesResponse")]
        Oleit.AS.Service.DataObject.Role[] QueryRoles(string userName, string roleName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAccess/CheckRole", ReplyAction="http://tempuri.org/IUserAccess/CheckRoleResponse")]
        bool CheckRole(string userName, Oleit.AS.Service.DataObject.Role role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAccess/GetAllRoles", ReplyAction="http://tempuri.org/IUserAccess/GetAllRolesResponse")]
        Oleit.AS.Service.DataObject.Role[] GetAllRoles(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAccess/GetMenu", ReplyAction="http://tempuri.org/IUserAccess/GetMenuResponse")]
        Oleit.AS.Service.DataObject.FuncMenu[] GetMenu(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAccess/CheckPassword", ReplyAction="http://tempuri.org/IUserAccess/CheckPasswordResponse")]
        bool CheckPassword(string userName, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserAccessChannel : Oleit.AS.Service.LogicService.UserAccessReference.IUserAccess, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserAccessClient : System.ServiceModel.ClientBase<Oleit.AS.Service.LogicService.UserAccessReference.IUserAccess>, Oleit.AS.Service.LogicService.UserAccessReference.IUserAccess {
        
        public UserAccessClient() {
        }
        
        public UserAccessClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserAccessClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserAccessClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserAccessClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Insertuser(Oleit.AS.Service.DataObject.User user) {
            base.Channel.Insertuser(user);
        }
        
        public void InsertuserCollection(Oleit.AS.Service.DataObject.User[] userCollection) {
            base.Channel.InsertuserCollection(userCollection);
        }
        
        public Oleit.AS.Service.DataObject.User[] QueryuserID(int userID) {
            return base.Channel.QueryuserID(userID);
        }
        
        public Oleit.AS.Service.DataObject.User[] QueryuserName(string userName) {
            return base.Channel.QueryuserName(userName);
        }
        
        public Oleit.AS.Service.DataObject.User[] QueryAll() {
            return base.Channel.QueryAll();
        }
        
        public void Updateuser(Oleit.AS.Service.DataObject.User user) {
            base.Channel.Updateuser(user);
        }
        
        public void UpdateuserCollection(Oleit.AS.Service.DataObject.User[] userCollection) {
            base.Channel.UpdateuserCollection(userCollection);
        }
        
        public void Disable(Oleit.AS.Service.DataObject.User[] userCollection) {
            base.Channel.Disable(userCollection);
        }
        
        public bool DisableUser(int userID) {
            return base.Channel.DisableUser(userID);
        }
        
        public void ChangePassword(string userName, string password) {
            base.Channel.ChangePassword(userName, password);
        }
        
        public void UpdateRoles(string userName, Oleit.AS.Service.DataObject.Role role) {
            base.Channel.UpdateRoles(userName, role);
        }
        
        public void UpdaterolesCollection(string userName, Oleit.AS.Service.DataObject.Role[] roleCollection) {
            base.Channel.UpdaterolesCollection(userName, roleCollection);
        }
        
        public Oleit.AS.Service.DataObject.Role[] QueryRoles(string userName, string roleName) {
            return base.Channel.QueryRoles(userName, roleName);
        }
        
        public bool CheckRole(string userName, Oleit.AS.Service.DataObject.Role role) {
            return base.Channel.CheckRole(userName, role);
        }
        
        public Oleit.AS.Service.DataObject.Role[] GetAllRoles(string userName) {
            return base.Channel.GetAllRoles(userName);
        }
        
        public Oleit.AS.Service.DataObject.FuncMenu[] GetMenu(string userName) {
            return base.Channel.GetMenu(userName);
        }
        
        public bool CheckPassword(string userName, string password) {
            return base.Channel.CheckPassword(userName, password);
        }
    }
}
