//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oleit.AS.Service.LogicService.EntityAccessReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EntityAccessReference.IEntityAccess")]
    public interface IEntityAccess {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityAccess/Insert1", ReplyAction="http://tempuri.org/IEntityAccess/Insert1Response")]
        int Insert1(Oleit.AS.Service.DataObject.Entity entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityAccess/Insert2", ReplyAction="http://tempuri.org/IEntityAccess/Insert2Response")]
        void Insert2(Oleit.AS.Service.DataObject.Entity entity, Oleit.AS.Service.DataObject.CashEntity cashEntity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityAccess/Insert3", ReplyAction="http://tempuri.org/IEntityAccess/Insert3Response")]
        void Insert3(Oleit.AS.Service.DataObject.Entity entity, Oleit.AS.Service.DataObject.Account account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityAccess/Insert4", ReplyAction="http://tempuri.org/IEntityAccess/Insert4Response")]
        void Insert4(Oleit.AS.Service.DataObject.Account account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityAccess/QueryRelationEntities", ReplyAction="http://tempuri.org/IEntityAccess/QueryRelationEntitiesResponse")]
        Oleit.AS.Service.DataObject.Entity[] QueryRelationEntities();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityAccess/QueryMainEntity", ReplyAction="http://tempuri.org/IEntityAccess/QueryMainEntityResponse")]
        Oleit.AS.Service.DataObject.Entity QueryMainEntity(int entityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityAccess/Query1", ReplyAction="http://tempuri.org/IEntityAccess/Query1Response")]
        Oleit.AS.Service.DataObject.Entity[] Query1();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityAccess/Query2", ReplyAction="http://tempuri.org/IEntityAccess/Query2Response")]
        Oleit.AS.Service.DataObject.Entity[] Query2(int entityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityAccess/Query3", ReplyAction="http://tempuri.org/IEntityAccess/Query3Response")]
        Oleit.AS.Service.DataObject.Entity[] Query3(string entityName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityAccess/Query4", ReplyAction="http://tempuri.org/IEntityAccess/Query4Response")]
        Oleit.AS.Service.DataObject.Entity[] Query4(Oleit.AS.Service.DataObject.EntityType _type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityAccess/QueryCashEntity1", ReplyAction="http://tempuri.org/IEntityAccess/QueryCashEntity1Response")]
        Oleit.AS.Service.DataObject.CashEntity[] QueryCashEntity1();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityAccess/QueryCashEntity2", ReplyAction="http://tempuri.org/IEntityAccess/QueryCashEntity2Response")]
        Oleit.AS.Service.DataObject.CashEntity[] QueryCashEntity2(int entityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityAccess/QueryCashEntity3", ReplyAction="http://tempuri.org/IEntityAccess/QueryCashEntity3Response")]
        Oleit.AS.Service.DataObject.CashEntity[] QueryCashEntity3(string contractNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityAccess/QueryAccount1", ReplyAction="http://tempuri.org/IEntityAccess/QueryAccount1Response")]
        Oleit.AS.Service.DataObject.Account[] QueryAccount1();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityAccess/QueryAccount2", ReplyAction="http://tempuri.org/IEntityAccess/QueryAccount2Response")]
        Oleit.AS.Service.DataObject.Account[] QueryAccount2(int entityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityAccess/QueryAccount3", ReplyAction="http://tempuri.org/IEntityAccess/QueryAccount3Response")]
        Oleit.AS.Service.DataObject.Account[] QueryAccount3(string accountName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityAccess/QuerySumEntity1", ReplyAction="http://tempuri.org/IEntityAccess/QuerySumEntity1Response")]
        Oleit.AS.Service.DataObject.Entity[] QuerySumEntity1(Oleit.AS.Service.DataObject.SumType sumType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityAccess/QuerySumEntity2", ReplyAction="http://tempuri.org/IEntityAccess/QuerySumEntity2Response")]
        Oleit.AS.Service.DataObject.Entity[] QuerySumEntity2(int entityID, Oleit.AS.Service.DataObject.SumType sumType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityAccess/QuerySubEntitiesList", ReplyAction="http://tempuri.org/IEntityAccess/QuerySubEntitiesListResponse")]
        Oleit.AS.Service.DataObject.Entity[] QuerySubEntitiesList(int entityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityAccess/QueryParentSubTotalEntity", ReplyAction="http://tempuri.org/IEntityAccess/QueryParentSubTotalEntityResponse")]
        Oleit.AS.Service.DataObject.Entity[] QueryParentSubTotalEntity(int entityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityAccess/QueryParentTransactionEntity", ReplyAction="http://tempuri.org/IEntityAccess/QueryParentTransactionEntityResponse")]
        Oleit.AS.Service.DataObject.Entity[] QueryParentTransactionEntity(int entityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityAccess/QueryAllSub1", ReplyAction="http://tempuri.org/IEntityAccess/QueryAllSub1Response")]
        Oleit.AS.Service.DataObject.Entity[] QueryAllSub1(int entityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityAccess/QueryAllSub2", ReplyAction="http://tempuri.org/IEntityAccess/QueryAllSub2Response")]
        Oleit.AS.Service.DataObject.Entity[] QueryAllSub2(string entityName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityAccess/Update1", ReplyAction="http://tempuri.org/IEntityAccess/Update1Response")]
        void Update1(Oleit.AS.Service.DataObject.Entity entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityAccess/Update2", ReplyAction="http://tempuri.org/IEntityAccess/Update2Response")]
        void Update2(Oleit.AS.Service.DataObject.Entity entity, Oleit.AS.Service.DataObject.CashEntity cashEntity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityAccess/Update3", ReplyAction="http://tempuri.org/IEntityAccess/Update3Response")]
        void Update3(int userID, Oleit.AS.Service.DataObject.Entity entity, Oleit.AS.Service.DataObject.Account account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityAccess/Disable", ReplyAction="http://tempuri.org/IEntityAccess/DisableResponse")]
        void Disable(int entityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityAccess/Enable", ReplyAction="http://tempuri.org/IEntityAccess/EnableResponse")]
        void Enable(int entityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityAccess/RemoveRelation", ReplyAction="http://tempuri.org/IEntityAccess/RemoveRelationResponse")]
        void RemoveRelation(int entityID, int targetEntityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityAccess/SetRate", ReplyAction="http://tempuri.org/IEntityAccess/SetRateResponse")]
        void SetRate(int entityID, decimal exchangeRate, Oleit.AS.Service.DataObject.Currency currency);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityAccess/ChangeStatus", ReplyAction="http://tempuri.org/IEntityAccess/ChangeStatusResponse")]
        void ChangeStatus(Oleit.AS.Service.DataObject.User user, int entityID, Oleit.AS.Service.DataObject.Status status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityAccess/SetAttributes", ReplyAction="http://tempuri.org/IEntityAccess/SetAttributesResponse")]
        void SetAttributes(Oleit.AS.Service.DataObject.User user, int entityID, Oleit.AS.Service.DataObject.Account account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityAccess/Allocate", ReplyAction="http://tempuri.org/IEntityAccess/AllocateResponse")]
        void Allocate(string accountname, int entityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityAccess/SetRelateEntity", ReplyAction="http://tempuri.org/IEntityAccess/SetRelateEntityResponse")]
        void SetRelateEntity(Oleit.AS.Service.DataObject.Relation relation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityAccess/GetRelateEntity", ReplyAction="http://tempuri.org/IEntityAccess/GetRelateEntityResponse")]
        Oleit.AS.Service.DataObject.Relation[] GetRelateEntity(int entityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityAccess/GetTallyRelationEntity", ReplyAction="http://tempuri.org/IEntityAccess/GetTallyRelationEntityResponse")]
        Oleit.AS.Service.DataObject.Relation[] GetTallyRelationEntity(int entityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityAccess/GetTargetRelation", ReplyAction="http://tempuri.org/IEntityAccess/GetTargetRelationResponse")]
        Oleit.AS.Service.DataObject.Relation[] GetTargetRelation(int targetEntityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityAccess/QueryRelation", ReplyAction="http://tempuri.org/IEntityAccess/QueryRelationResponse")]
        Oleit.AS.Service.DataObject.Entity[] QueryRelation(int _entityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityAccess/QueryAllMLJ", ReplyAction="http://tempuri.org/IEntityAccess/QueryAllMLJResponse")]
        Oleit.AS.Service.DataObject.Entity[] QueryAllMLJ(int entityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityAccess/GetRelateEntityWandL", ReplyAction="http://tempuri.org/IEntityAccess/GetRelateEntityWandLResponse")]
        Oleit.AS.Service.DataObject.Relation[] GetRelateEntityWandL(int entityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityAccess/QueryAllSubEntity", ReplyAction="http://tempuri.org/IEntityAccess/QueryAllSubEntityResponse")]
        Oleit.AS.Service.DataObject.Entity[] QueryAllSubEntity(int entityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityAccess/QueryMainCash", ReplyAction="http://tempuri.org/IEntityAccess/QueryMainCashResponse")]
        Oleit.AS.Service.DataObject.Entity[] QueryMainCash();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityAccess/QueryTransactionList", ReplyAction="http://tempuri.org/IEntityAccess/QueryTransactionListResponse")]
        Oleit.AS.Service.DataObject.Entity[] QueryTransactionList(int entityID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEntityAccessChannel : Oleit.AS.Service.LogicService.EntityAccessReference.IEntityAccess, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EntityAccessClient : System.ServiceModel.ClientBase<Oleit.AS.Service.LogicService.EntityAccessReference.IEntityAccess>, Oleit.AS.Service.LogicService.EntityAccessReference.IEntityAccess {
        
        public EntityAccessClient() {
        }
        
        public EntityAccessClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EntityAccessClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EntityAccessClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EntityAccessClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Insert1(Oleit.AS.Service.DataObject.Entity entity) {
            return base.Channel.Insert1(entity);
        }
        
        public void Insert2(Oleit.AS.Service.DataObject.Entity entity, Oleit.AS.Service.DataObject.CashEntity cashEntity) {
            base.Channel.Insert2(entity, cashEntity);
        }
        
        public void Insert3(Oleit.AS.Service.DataObject.Entity entity, Oleit.AS.Service.DataObject.Account account) {
            base.Channel.Insert3(entity, account);
        }
        
        public void Insert4(Oleit.AS.Service.DataObject.Account account) {
            base.Channel.Insert4(account);
        }
        
        public Oleit.AS.Service.DataObject.Entity[] QueryRelationEntities() {
            return base.Channel.QueryRelationEntities();
        }
        
        public Oleit.AS.Service.DataObject.Entity QueryMainEntity(int entityID) {
            return base.Channel.QueryMainEntity(entityID);
        }
        
        public Oleit.AS.Service.DataObject.Entity[] Query1() {
            return base.Channel.Query1();
        }
        
        public Oleit.AS.Service.DataObject.Entity[] Query2(int entityID) {
            return base.Channel.Query2(entityID);
        }
        
        public Oleit.AS.Service.DataObject.Entity[] Query3(string entityName) {
            return base.Channel.Query3(entityName);
        }
        
        public Oleit.AS.Service.DataObject.Entity[] Query4(Oleit.AS.Service.DataObject.EntityType _type) {
            return base.Channel.Query4(_type);
        }
        
        public Oleit.AS.Service.DataObject.CashEntity[] QueryCashEntity1() {
            return base.Channel.QueryCashEntity1();
        }
        
        public Oleit.AS.Service.DataObject.CashEntity[] QueryCashEntity2(int entityID) {
            return base.Channel.QueryCashEntity2(entityID);
        }
        
        public Oleit.AS.Service.DataObject.CashEntity[] QueryCashEntity3(string contractNumber) {
            return base.Channel.QueryCashEntity3(contractNumber);
        }
        
        public Oleit.AS.Service.DataObject.Account[] QueryAccount1() {
            return base.Channel.QueryAccount1();
        }
        
        public Oleit.AS.Service.DataObject.Account[] QueryAccount2(int entityID) {
            return base.Channel.QueryAccount2(entityID);
        }
        
        public Oleit.AS.Service.DataObject.Account[] QueryAccount3(string accountName) {
            return base.Channel.QueryAccount3(accountName);
        }
        
        public Oleit.AS.Service.DataObject.Entity[] QuerySumEntity1(Oleit.AS.Service.DataObject.SumType sumType) {
            return base.Channel.QuerySumEntity1(sumType);
        }
        
        public Oleit.AS.Service.DataObject.Entity[] QuerySumEntity2(int entityID, Oleit.AS.Service.DataObject.SumType sumType) {
            return base.Channel.QuerySumEntity2(entityID, sumType);
        }
        
        public Oleit.AS.Service.DataObject.Entity[] QuerySubEntitiesList(int entityID) {
            return base.Channel.QuerySubEntitiesList(entityID);
        }
        
        public Oleit.AS.Service.DataObject.Entity[] QueryParentSubTotalEntity(int entityID) {
            return base.Channel.QueryParentSubTotalEntity(entityID);
        }
        
        public Oleit.AS.Service.DataObject.Entity[] QueryParentTransactionEntity(int entityID) {
            return base.Channel.QueryParentTransactionEntity(entityID);
        }
        
        public Oleit.AS.Service.DataObject.Entity[] QueryAllSub1(int entityID) {
            return base.Channel.QueryAllSub1(entityID);
        }
        
        public Oleit.AS.Service.DataObject.Entity[] QueryAllSub2(string entityName) {
            return base.Channel.QueryAllSub2(entityName);
        }
        
        public void Update1(Oleit.AS.Service.DataObject.Entity entity) {
            base.Channel.Update1(entity);
        }
        
        public void Update2(Oleit.AS.Service.DataObject.Entity entity, Oleit.AS.Service.DataObject.CashEntity cashEntity) {
            base.Channel.Update2(entity, cashEntity);
        }
        
        public void Update3(int userID, Oleit.AS.Service.DataObject.Entity entity, Oleit.AS.Service.DataObject.Account account) {
            base.Channel.Update3(userID, entity, account);
        }
        
        public void Disable(int entityID) {
            base.Channel.Disable(entityID);
        }
        
        public void Enable(int entityID) {
            base.Channel.Enable(entityID);
        }
        
        public void RemoveRelation(int entityID, int targetEntityID) {
            base.Channel.RemoveRelation(entityID, targetEntityID);
        }
        
        public void SetRate(int entityID, decimal exchangeRate, Oleit.AS.Service.DataObject.Currency currency) {
            base.Channel.SetRate(entityID, exchangeRate, currency);
        }
        
        public void ChangeStatus(Oleit.AS.Service.DataObject.User user, int entityID, Oleit.AS.Service.DataObject.Status status) {
            base.Channel.ChangeStatus(user, entityID, status);
        }
        
        public void SetAttributes(Oleit.AS.Service.DataObject.User user, int entityID, Oleit.AS.Service.DataObject.Account account) {
            base.Channel.SetAttributes(user, entityID, account);
        }
        
        public void Allocate(string accountname, int entityID) {
            base.Channel.Allocate(accountname, entityID);
        }
        
        public void SetRelateEntity(Oleit.AS.Service.DataObject.Relation relation) {
            base.Channel.SetRelateEntity(relation);
        }
        
        public Oleit.AS.Service.DataObject.Relation[] GetRelateEntity(int entityID) {
            return base.Channel.GetRelateEntity(entityID);
        }
        
        public Oleit.AS.Service.DataObject.Relation[] GetTallyRelationEntity(int entityID) {
            return base.Channel.GetTallyRelationEntity(entityID);
        }
        
        public Oleit.AS.Service.DataObject.Relation[] GetTargetRelation(int targetEntityID) {
            return base.Channel.GetTargetRelation(targetEntityID);
        }
        
        public Oleit.AS.Service.DataObject.Entity[] QueryRelation(int _entityID) {
            return base.Channel.QueryRelation(_entityID);
        }
        
        public Oleit.AS.Service.DataObject.Entity[] QueryAllMLJ(int entityID) {
            return base.Channel.QueryAllMLJ(entityID);
        }
        
        public Oleit.AS.Service.DataObject.Relation[] GetRelateEntityWandL(int entityID) {
            return base.Channel.GetRelateEntityWandL(entityID);
        }
        
        public Oleit.AS.Service.DataObject.Entity[] QueryAllSubEntity(int entityID) {
            return base.Channel.QueryAllSubEntity(entityID);
        }
        
        public Oleit.AS.Service.DataObject.Entity[] QueryMainCash() {
            return base.Channel.QueryMainCash();
        }
        
        public Oleit.AS.Service.DataObject.Entity[] QueryTransactionList(int entityID) {
            return base.Channel.QueryTransactionList(entityID);
        }
    }
}
