//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting_System.EntityServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EntityServiceReference.IEntityService")]
    public interface IEntityService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/NewEntity1", ReplyAction="http://tempuri.org/IEntityService/NewEntity1Response")]
        void NewEntity1(Oleit.AS.Service.DataObject.Entity entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/NewEntity2", ReplyAction="http://tempuri.org/IEntityService/NewEntity2Response")]
        void NewEntity2(Oleit.AS.Service.DataObject.Entity entity, Oleit.AS.Service.DataObject.CashEntity cashEntity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/NewEntity3", ReplyAction="http://tempuri.org/IEntityService/NewEntity3Response")]
        void NewEntity3(Oleit.AS.Service.DataObject.Entity entity, Oleit.AS.Service.DataObject.Account account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/LoadEntity1", ReplyAction="http://tempuri.org/IEntityService/LoadEntity1Response")]
        Oleit.AS.Service.DataObject.Entity[] LoadEntity1();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/LoadAll", ReplyAction="http://tempuri.org/IEntityService/LoadAllResponse")]
        Oleit.AS.Service.DataObject.Entity[] LoadAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/LoadEntity2", ReplyAction="http://tempuri.org/IEntityService/LoadEntity2Response")]
        Oleit.AS.Service.DataObject.Entity[] LoadEntity2(int entityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/LoadEntity3", ReplyAction="http://tempuri.org/IEntityService/LoadEntity3Response")]
        Oleit.AS.Service.DataObject.Entity[] LoadEntity3(string entityName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/LoadEntity4", ReplyAction="http://tempuri.org/IEntityService/LoadEntity4Response")]
        Oleit.AS.Service.DataObject.Entity[] LoadEntity4(int[] entityIDs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/LoadAccountEntities", ReplyAction="http://tempuri.org/IEntityService/LoadAccountEntitiesResponse")]
        Oleit.AS.Service.DataObject.Entity[] LoadAccountEntities(int parentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/LoadLastLevelEntities", ReplyAction="http://tempuri.org/IEntityService/LoadLastLevelEntitiesResponse")]
        Oleit.AS.Service.DataObject.Entity[] LoadLastLevelEntities(int parentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/QueryRelationEntities", ReplyAction="http://tempuri.org/IEntityService/QueryRelationEntitiesResponse")]
        Oleit.AS.Service.DataObject.Entity[] QueryRelationEntities();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/LoadSingleEntityList", ReplyAction="http://tempuri.org/IEntityService/LoadSingleEntityListResponse")]
        Oleit.AS.Service.DataObject.Entity[] LoadSingleEntityList(int entityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/QuerySubEntitiesList", ReplyAction="http://tempuri.org/IEntityService/QuerySubEntitiesListResponse")]
        Oleit.AS.Service.DataObject.Entity[] QuerySubEntitiesList(int entityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/QuerySingleBranchEntity", ReplyAction="http://tempuri.org/IEntityService/QuerySingleBranchEntityResponse")]
        string QuerySingleBranchEntity(int entityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/LoadCashEntity1", ReplyAction="http://tempuri.org/IEntityService/LoadCashEntity1Response")]
        Oleit.AS.Service.DataObject.CashEntity[] LoadCashEntity1();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/QueryMainEntity", ReplyAction="http://tempuri.org/IEntityService/QueryMainEntityResponse")]
        Oleit.AS.Service.DataObject.Entity QueryMainEntity(int entityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/LoadCashEntity2", ReplyAction="http://tempuri.org/IEntityService/LoadCashEntity2Response")]
        Oleit.AS.Service.DataObject.CashEntity[] LoadCashEntity2(int entityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/LoadCashEntity3", ReplyAction="http://tempuri.org/IEntityService/LoadCashEntity3Response")]
        Oleit.AS.Service.DataObject.CashEntity[] LoadCashEntity3(string contractNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/LoadAccount1", ReplyAction="http://tempuri.org/IEntityService/LoadAccount1Response")]
        Oleit.AS.Service.DataObject.Account[] LoadAccount1();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/LoadAccount2", ReplyAction="http://tempuri.org/IEntityService/LoadAccount2Response")]
        Oleit.AS.Service.DataObject.Account[] LoadAccount2(int entityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/LoadAccount3", ReplyAction="http://tempuri.org/IEntityService/LoadAccount3Response")]
        Oleit.AS.Service.DataObject.Account[] LoadAccount3(string accountName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/LoadSubtotalEntity1", ReplyAction="http://tempuri.org/IEntityService/LoadSubtotalEntity1Response")]
        Oleit.AS.Service.DataObject.Entity[] LoadSubtotalEntity1();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/QueryParentSubTotalEntity", ReplyAction="http://tempuri.org/IEntityService/QueryParentSubTotalEntityResponse")]
        Oleit.AS.Service.DataObject.Entity[] QueryParentSubTotalEntity(int entityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/LoadTransactionEntity1", ReplyAction="http://tempuri.org/IEntityService/LoadTransactionEntity1Response")]
        Oleit.AS.Service.DataObject.Entity[] LoadTransactionEntity1();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/LoadTransactionEntity2", ReplyAction="http://tempuri.org/IEntityService/LoadTransactionEntity2Response")]
        Oleit.AS.Service.DataObject.Entity[] LoadTransactionEntity2(int entityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/SaveEntity1", ReplyAction="http://tempuri.org/IEntityService/SaveEntity1Response")]
        void SaveEntity1(Oleit.AS.Service.DataObject.Entity entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/SaveEntity2", ReplyAction="http://tempuri.org/IEntityService/SaveEntity2Response")]
        void SaveEntity2(Oleit.AS.Service.DataObject.Entity entity, Oleit.AS.Service.DataObject.CashEntity cashEntity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/SaveEntity3", ReplyAction="http://tempuri.org/IEntityService/SaveEntity3Response")]
        void SaveEntity3(int userID, Oleit.AS.Service.DataObject.Entity entity, Oleit.AS.Service.DataObject.Account account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/ChangeEntityType", ReplyAction="http://tempuri.org/IEntityService/ChangeEntityTypeResponse")]
        void ChangeEntityType(int entityID, Oleit.AS.Service.DataObject.EntityType type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/NewRelation", ReplyAction="http://tempuri.org/IEntityService/NewRelationResponse")]
        void NewRelation(Oleit.AS.Service.DataObject.Relation relation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/SetRelation", ReplyAction="http://tempuri.org/IEntityService/SetRelationResponse")]
        void SetRelation(int entityID, Oleit.AS.Service.DataObject.Relation relation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/SetCurrencyAndRate", ReplyAction="http://tempuri.org/IEntityService/SetCurrencyAndRateResponse")]
        void SetCurrencyAndRate(int entityID, string currencyID, decimal rate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/ChangeRate", ReplyAction="http://tempuri.org/IEntityService/ChangeRateResponse")]
        void ChangeRate(int entityID, decimal rate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/Disable", ReplyAction="http://tempuri.org/IEntityService/DisableResponse")]
        void Disable(int entityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/Enable", ReplyAction="http://tempuri.org/IEntityService/EnableResponse")]
        void Enable(int entityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/RemoveRelation", ReplyAction="http://tempuri.org/IEntityService/RemoveRelationResponse")]
        void RemoveRelation(int entityID, int targetEntityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/GetEntryEntities", ReplyAction="http://tempuri.org/IEntityService/GetEntryEntitiesResponse")]
        Oleit.AS.Service.DataObject.Entity[] GetEntryEntities(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/GetRelateEntity", ReplyAction="http://tempuri.org/IEntityService/GetRelateEntityResponse")]
        Oleit.AS.Service.DataObject.Relation[] GetRelateEntity(int entityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/ChangeStatus", ReplyAction="http://tempuri.org/IEntityService/ChangeStatusResponse")]
        void ChangeStatus(Oleit.AS.Service.DataObject.User user, int entityID, Oleit.AS.Service.DataObject.Status status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/RelationEntity", ReplyAction="http://tempuri.org/IEntityService/RelationEntityResponse")]
        Oleit.AS.Service.DataObject.Relation[] RelationEntity(int _entityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/RelationEntityWandL", ReplyAction="http://tempuri.org/IEntityService/RelationEntityWandLResponse")]
        Oleit.AS.Service.DataObject.Relation[] RelationEntityWandL(int _entityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/QueryAllMLJ", ReplyAction="http://tempuri.org/IEntityService/QueryAllMLJResponse")]
        Oleit.AS.Service.DataObject.Entity[] QueryAllMLJ(int entityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/LoadCashMainAndTransaction", ReplyAction="http://tempuri.org/IEntityService/LoadCashMainAndTransactionResponse")]
        Oleit.AS.Service.DataObject.Entity[] LoadCashMainAndTransaction();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntityService/CheckTransactionTransfer", ReplyAction="http://tempuri.org/IEntityService/CheckTransactionTransferResponse")]
        Oleit.AS.Service.DataObject.Entity[] CheckTransactionTransfer(int entityID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEntityServiceChannel : Accounting_System.EntityServiceReference.IEntityService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EntityServiceClient : System.ServiceModel.ClientBase<Accounting_System.EntityServiceReference.IEntityService>, Accounting_System.EntityServiceReference.IEntityService {
        
        public EntityServiceClient() {
        }
        
        public EntityServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EntityServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EntityServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EntityServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void NewEntity1(Oleit.AS.Service.DataObject.Entity entity) {
            base.Channel.NewEntity1(entity);
        }
        
        public void NewEntity2(Oleit.AS.Service.DataObject.Entity entity, Oleit.AS.Service.DataObject.CashEntity cashEntity) {
            base.Channel.NewEntity2(entity, cashEntity);
        }
        
        public void NewEntity3(Oleit.AS.Service.DataObject.Entity entity, Oleit.AS.Service.DataObject.Account account) {
            base.Channel.NewEntity3(entity, account);
        }
        
        public Oleit.AS.Service.DataObject.Entity[] LoadEntity1() {
            return base.Channel.LoadEntity1();
        }
        
        public Oleit.AS.Service.DataObject.Entity[] LoadAll() {
            return base.Channel.LoadAll();
        }
        
        public Oleit.AS.Service.DataObject.Entity[] LoadEntity2(int entityID) {
            return base.Channel.LoadEntity2(entityID);
        }
        
        public Oleit.AS.Service.DataObject.Entity[] LoadEntity3(string entityName) {
            return base.Channel.LoadEntity3(entityName);
        }
        
        public Oleit.AS.Service.DataObject.Entity[] LoadEntity4(int[] entityIDs) {
            return base.Channel.LoadEntity4(entityIDs);
        }
        
        public Oleit.AS.Service.DataObject.Entity[] LoadAccountEntities(int parentID) {
            return base.Channel.LoadAccountEntities(parentID);
        }
        
        public Oleit.AS.Service.DataObject.Entity[] LoadLastLevelEntities(int parentID) {
            return base.Channel.LoadLastLevelEntities(parentID);
        }
        
        public Oleit.AS.Service.DataObject.Entity[] QueryRelationEntities() {
            return base.Channel.QueryRelationEntities();
        }
        
        public Oleit.AS.Service.DataObject.Entity[] LoadSingleEntityList(int entityID) {
            return base.Channel.LoadSingleEntityList(entityID);
        }
        
        public Oleit.AS.Service.DataObject.Entity[] QuerySubEntitiesList(int entityID) {
            return base.Channel.QuerySubEntitiesList(entityID);
        }
        
        public string QuerySingleBranchEntity(int entityID) {
            return base.Channel.QuerySingleBranchEntity(entityID);
        }
        
        public Oleit.AS.Service.DataObject.CashEntity[] LoadCashEntity1() {
            return base.Channel.LoadCashEntity1();
        }
        
        public Oleit.AS.Service.DataObject.Entity QueryMainEntity(int entityID) {
            return base.Channel.QueryMainEntity(entityID);
        }
        
        public Oleit.AS.Service.DataObject.CashEntity[] LoadCashEntity2(int entityID) {
            return base.Channel.LoadCashEntity2(entityID);
        }
        
        public Oleit.AS.Service.DataObject.CashEntity[] LoadCashEntity3(string contractNumber) {
            return base.Channel.LoadCashEntity3(contractNumber);
        }
        
        public Oleit.AS.Service.DataObject.Account[] LoadAccount1() {
            return base.Channel.LoadAccount1();
        }
        
        public Oleit.AS.Service.DataObject.Account[] LoadAccount2(int entityID) {
            return base.Channel.LoadAccount2(entityID);
        }
        
        public Oleit.AS.Service.DataObject.Account[] LoadAccount3(string accountName) {
            return base.Channel.LoadAccount3(accountName);
        }
        
        public Oleit.AS.Service.DataObject.Entity[] LoadSubtotalEntity1() {
            return base.Channel.LoadSubtotalEntity1();
        }
        
        public Oleit.AS.Service.DataObject.Entity[] QueryParentSubTotalEntity(int entityID) {
            return base.Channel.QueryParentSubTotalEntity(entityID);
        }
        
        public Oleit.AS.Service.DataObject.Entity[] LoadTransactionEntity1() {
            return base.Channel.LoadTransactionEntity1();
        }
        
        public Oleit.AS.Service.DataObject.Entity[] LoadTransactionEntity2(int entityID) {
            return base.Channel.LoadTransactionEntity2(entityID);
        }
        
        public void SaveEntity1(Oleit.AS.Service.DataObject.Entity entity) {
            base.Channel.SaveEntity1(entity);
        }
        
        public void SaveEntity2(Oleit.AS.Service.DataObject.Entity entity, Oleit.AS.Service.DataObject.CashEntity cashEntity) {
            base.Channel.SaveEntity2(entity, cashEntity);
        }
        
        public void SaveEntity3(int userID, Oleit.AS.Service.DataObject.Entity entity, Oleit.AS.Service.DataObject.Account account) {
            base.Channel.SaveEntity3(userID, entity, account);
        }
        
        public void ChangeEntityType(int entityID, Oleit.AS.Service.DataObject.EntityType type) {
            base.Channel.ChangeEntityType(entityID, type);
        }
        
        public void NewRelation(Oleit.AS.Service.DataObject.Relation relation) {
            base.Channel.NewRelation(relation);
        }
        
        public void SetRelation(int entityID, Oleit.AS.Service.DataObject.Relation relation) {
            base.Channel.SetRelation(entityID, relation);
        }
        
        public void SetCurrencyAndRate(int entityID, string currencyID, decimal rate) {
            base.Channel.SetCurrencyAndRate(entityID, currencyID, rate);
        }
        
        public void ChangeRate(int entityID, decimal rate) {
            base.Channel.ChangeRate(entityID, rate);
        }
        
        public void Disable(int entityID) {
            base.Channel.Disable(entityID);
        }
        
        public void Enable(int entityID) {
            base.Channel.Enable(entityID);
        }
        
        public void RemoveRelation(int entityID, int targetEntityID) {
            base.Channel.RemoveRelation(entityID, targetEntityID);
        }
        
        public Oleit.AS.Service.DataObject.Entity[] GetEntryEntities(string userName) {
            return base.Channel.GetEntryEntities(userName);
        }
        
        public Oleit.AS.Service.DataObject.Relation[] GetRelateEntity(int entityID) {
            return base.Channel.GetRelateEntity(entityID);
        }
        
        public void ChangeStatus(Oleit.AS.Service.DataObject.User user, int entityID, Oleit.AS.Service.DataObject.Status status) {
            base.Channel.ChangeStatus(user, entityID, status);
        }
        
        public Oleit.AS.Service.DataObject.Relation[] RelationEntity(int _entityID) {
            return base.Channel.RelationEntity(_entityID);
        }
        
        public Oleit.AS.Service.DataObject.Relation[] RelationEntityWandL(int _entityID) {
            return base.Channel.RelationEntityWandL(_entityID);
        }
        
        public Oleit.AS.Service.DataObject.Entity[] QueryAllMLJ(int entityID) {
            return base.Channel.QueryAllMLJ(entityID);
        }
        
        public Oleit.AS.Service.DataObject.Entity[] LoadCashMainAndTransaction() {
            return base.Channel.LoadCashMainAndTransaction();
        }
        
        public Oleit.AS.Service.DataObject.Entity[] CheckTransactionTransfer(int entityID) {
            return base.Channel.CheckTransactionTransfer(entityID);
        }
    }
}
